### ISSUE TITLE
在火狐48等低版本浏览器中，可以拖拽滚动条，但是使用鼠标滚轮无效~

### ISSUE THREAD

**Issue by xsdream** [chenjiaj/c-scrollbar#2]

**Comment by xsdream** [comment]
我查了文档，mdn中写的overflow: -moz-scrollbars-none;   等于 overflow：hidden ，然后我进行测试，确实是这个导致无法滚动

**Comment by xsdream** [comment]
如果只是想兼容高版本的狐火，可以使用其他属性来替换overflow: -moz-scrollbars-none; 类似于 scrollbar-width: none; 。到此为止应该可以说是一个bug。但是我想让这个插件能够兼容低版本的firefox,因为我们项目中需要（有点强人所难），我看您已经完成了滚动条的mousedown方法，能否将@scroll的方式取消掉，改为监听鼠标滑轮的滚动，再去改变滚动条的位置。

**Comment by chenjiaj** [comment]
谢谢你的反馈，overflow: -moz-scrollbars-none 样式已经删除，包已经更新，你可以测试下是否满足你的需求。火狐48确实有点太老了，因为精力有限且目前接触的需求暂都对低版本无要求，因此低版本目前暂未准备支持，新版本chrome、edge、火狐经测试均无问题。如果你有特殊需求，可以直接将源代码Scrollbar文件夹引入项目中，可以根据你的需求进行修改。
