### ISSUE TITLE
小bug

### ISSUE THREAD

**Issue by weijianjunwjj** [chenjiaj/c-scrollbar#4]
作者大大您好，我用了你的插件感觉非常好。就是在点击滚动轴拖动的时候，控制台一直打印dom。请问您有空的时候，可不可以删掉啊？这样就更完美了！谢谢！
![image](https://user-images.githubusercontent.com/46668373/148056657-00c19f54-9c00-494c-9b97-99d689999b02.png)

**Comment by chenjiaj** [comment]
感谢使用，已经修复至c-scrollbar@1.0.2，更新依赖即可使用

**Comment by weijianjunwjj** [comment]
好的，辛苦了！
